// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: x3plus.proto
#ifndef GRPC_x3plus_2eproto__INCLUDED
#define GRPC_x3plus_2eproto__INCLUDED

#include "x3plus.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace x3plus {

// The RosmasterServices definition.
class RosmasterServices final {
 public:
  static constexpr char const* service_full_name() {
    return "x3plus.RosmasterServices";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::x3plus::JointPosititonArray* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>> AsyncgetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>>(AsyncgetJointPositionArrayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>> PrepareAsyncgetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>>(PrepareAsyncgetJointPositionArrayRaw(context, request, cq));
    }
    virtual ::grpc::Status setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::x3plus::ResultResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>> AsyncsetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>>(AsyncsetJointPositionArrayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>> PrepareAsyncsetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>>(PrepareAsyncsetJointPositionArrayRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>* AsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::JointPosititonArray>* PrepareAsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>* AsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::x3plus::ResultResponse>* PrepareAsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::x3plus::JointPosititonArray* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>> AsyncgetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>>(AsyncgetJointPositionArrayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>> PrepareAsyncgetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>>(PrepareAsyncgetJointPositionArrayRaw(context, request, cq));
    }
    ::grpc::Status setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::x3plus::ResultResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>> AsyncsetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>>(AsyncsetJointPositionArrayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>> PrepareAsyncsetJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>>(PrepareAsyncsetJointPositionArrayRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, std::function<void(::grpc::Status)>) override;
      void getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, ::grpc::ClientUnaryReactor* reactor) override;
      void setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, std::function<void(::grpc::Status)>) override;
      void setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>* AsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>* PrepareAsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>* AsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>* PrepareAsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getJointPositionArray_;
    const ::grpc::internal::RpcMethod rpcmethod_setJointPositionArray_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getJointPositionArray(::grpc::ServerContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response);
    virtual ::grpc::Status setJointPositionArray(::grpc::ServerContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetJointPositionArray(::grpc::ServerContext* context, ::x3plus::Empty* request, ::grpc::ServerAsyncResponseWriter< ::x3plus::JointPosititonArray>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetJointPositionArray(::grpc::ServerContext* context, ::x3plus::JointPosititonArray* request, ::grpc::ServerAsyncResponseWriter< ::x3plus::ResultResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getJointPositionArray<WithAsyncMethod_setJointPositionArray<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::x3plus::Empty, ::x3plus::JointPosititonArray>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response) { return this->getJointPositionArray(context, request, response); }));}
    void SetMessageAllocatorFor_getJointPositionArray(
        ::grpc::MessageAllocator< ::x3plus::Empty, ::x3plus::JointPosititonArray>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::x3plus::Empty, ::x3plus::JointPosititonArray>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getJointPositionArray(
      ::grpc::CallbackServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::x3plus::JointPosititonArray, ::x3plus::ResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response) { return this->setJointPositionArray(context, request, response); }));}
    void SetMessageAllocatorFor_setJointPositionArray(
        ::grpc::MessageAllocator< ::x3plus::JointPosititonArray, ::x3plus::ResultResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::x3plus::JointPosititonArray, ::x3plus::ResultResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setJointPositionArray(
      ::grpc::CallbackServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getJointPositionArray<WithCallbackMethod_setJointPositionArray<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetJointPositionArray(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetJointPositionArray(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getJointPositionArray(context, request, response); }));
    }
    ~WithRawCallbackMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getJointPositionArray(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setJointPositionArray(context, request, response); }));
    }
    ~WithRawCallbackMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setJointPositionArray(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getJointPositionArray() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::x3plus::Empty, ::x3plus::JointPosititonArray>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::x3plus::Empty, ::x3plus::JointPosititonArray>* streamer) {
                       return this->StreamedgetJointPositionArray(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::Empty* /*request*/, ::x3plus::JointPosititonArray* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetJointPositionArray(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::x3plus::Empty,::x3plus::JointPosititonArray>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setJointPositionArray : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setJointPositionArray() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::x3plus::JointPosititonArray, ::x3plus::ResultResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::x3plus::JointPosititonArray, ::x3plus::ResultResponse>* streamer) {
                       return this->StreamedsetJointPositionArray(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setJointPositionArray() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setJointPositionArray(::grpc::ServerContext* /*context*/, const ::x3plus::JointPosititonArray* /*request*/, ::x3plus::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetJointPositionArray(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::x3plus::JointPosititonArray,::x3plus::ResultResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getJointPositionArray<WithStreamedUnaryMethod_setJointPositionArray<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getJointPositionArray<WithStreamedUnaryMethod_setJointPositionArray<Service > > StreamedService;
};

}  // namespace x3plus


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_x3plus_2eproto__INCLUDED
