// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: x3plus.proto

#include "x3plus.pb.h"
#include "x3plus.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace x3plus {

static const char* RosmasterServices_method_names[] = {
  "/x3plus.RosmasterServices/getJointPositionArray",
  "/x3plus.RosmasterServices/setJointPositionArray",
};

std::unique_ptr< RosmasterServices::Stub> RosmasterServices::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RosmasterServices::Stub> stub(new RosmasterServices::Stub(channel, options));
  return stub;
}

RosmasterServices::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getJointPositionArray_(RosmasterServices_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setJointPositionArray_(RosmasterServices_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RosmasterServices::Stub::getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::x3plus::JointPosititonArray* response) {
  return ::grpc::internal::BlockingUnaryCall< ::x3plus::Empty, ::x3plus::JointPosititonArray, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getJointPositionArray_, context, request, response);
}

void RosmasterServices::Stub::async::getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::x3plus::Empty, ::x3plus::JointPosititonArray, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getJointPositionArray_, context, request, response, std::move(f));
}

void RosmasterServices::Stub::async::getJointPositionArray(::grpc::ClientContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getJointPositionArray_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>* RosmasterServices::Stub::PrepareAsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::x3plus::JointPosititonArray, ::x3plus::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getJointPositionArray_, context, request);
}

::grpc::ClientAsyncResponseReader< ::x3plus::JointPosititonArray>* RosmasterServices::Stub::AsyncgetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetJointPositionArrayRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RosmasterServices::Stub::setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::x3plus::ResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::x3plus::JointPosititonArray, ::x3plus::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setJointPositionArray_, context, request, response);
}

void RosmasterServices::Stub::async::setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::x3plus::JointPosititonArray, ::x3plus::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setJointPositionArray_, context, request, response, std::move(f));
}

void RosmasterServices::Stub::async::setJointPositionArray(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setJointPositionArray_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>* RosmasterServices::Stub::PrepareAsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::x3plus::ResultResponse, ::x3plus::JointPosititonArray, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setJointPositionArray_, context, request);
}

::grpc::ClientAsyncResponseReader< ::x3plus::ResultResponse>* RosmasterServices::Stub::AsyncsetJointPositionArrayRaw(::grpc::ClientContext* context, const ::x3plus::JointPosititonArray& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetJointPositionArrayRaw(context, request, cq);
  result->StartCall();
  return result;
}

RosmasterServices::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RosmasterServices_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RosmasterServices::Service, ::x3plus::Empty, ::x3plus::JointPosititonArray, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RosmasterServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::x3plus::Empty* req,
             ::x3plus::JointPosititonArray* resp) {
               return service->getJointPositionArray(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RosmasterServices_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RosmasterServices::Service, ::x3plus::JointPosititonArray, ::x3plus::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RosmasterServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::x3plus::JointPosititonArray* req,
             ::x3plus::ResultResponse* resp) {
               return service->setJointPositionArray(ctx, req, resp);
             }, this)));
}

RosmasterServices::Service::~Service() {
}

::grpc::Status RosmasterServices::Service::getJointPositionArray(::grpc::ServerContext* context, const ::x3plus::Empty* request, ::x3plus::JointPosititonArray* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RosmasterServices::Service::setJointPositionArray(::grpc::ServerContext* context, const ::x3plus::JointPosititonArray* request, ::x3plus::ResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace x3plus
#include <grpcpp/ports_undef.inc>

